"""
KalaSetu — Rich Product Catalog Seed Script
Seeds 20+ authentic handcraft products covering all major categories.
Run: python scripts/seed_products.py
"""
import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "artisan_catalog.db")

PRODUCTS = [
    # ── Handloom & Textiles ──────────────────────────────────────────────────
    {
        "name": "Natural Indigo Bhagalpur Tussar Silk Saree",
        "artisan_name": "Manjula Ansari",
        "artisan_phone": "+919876501001",
        "artisan_location": "Bhagalpur, Bihar",
        "category": "Handloom & Textiles",
        "price": 3450,
        "suggested_price_min": 3000,
        "suggested_price_max": 4200,
        "description_en": "Pure handloom wild Tussar silk saree hand-dyed with organic indigo using traditional Bhagalpur weaving technique. Features fine natural texture with subtle sheen, 5.5 meters length, 47-inch width, with unstitched blouse piece. GI-tagged Bhagalpur silk.",
        "description_hi": "Shudh hathkargha jangali tsar reshmi sari jo jaivik nil se rangi gayi hai. Bhagalpur bunai taknik se nirmit.",
        "tags": "saree,silk,tussar,indigo,bhagalpur,bihar,handloom,GI-tagged,natural-dye",
        "image_url": "/static/uploads/saree_indigo.jpg",
        "quantity": 8,
        "rating": 4.8,
    },
    {
        "name": "Kanjivaram Pure Silk Temple Border Saree",
        "artisan_name": "Meenakshi Murugan",
        "artisan_phone": "+919876501002",
        "artisan_location": "Kanchipuram, Tamil Nadu",
        "category": "Handloom & Textiles",
        "price": 7800,
        "suggested_price_min": 7000,
        "suggested_price_max": 9000,
        "description_en": "Authentic Kanjivaram pure mulberry silk saree with zari temple border and traditional paisley motifs. Weighs approx 800g indicating pure silk density. Bright ruby red body with contrast golden-green border. Comes with authenticity certificate.",
        "description_hi": "Pramaanik Kanjivaram shudh reshmi sari, zari mandir border aur paramparik paisley design ke saath.",
        "tags": "kanjivaram,silk,saree,temple-border,zari,kanchipuram,GI-tagged,bridal",
        "image_url": "/static/uploads/kanjivaram_saree.jpg",
        "quantity": 5,
        "rating": 4.9,
    },
    {
        "name": "Pochampally Double Ikat Cotton Dress Material",
        "artisan_name": "Laxmi Bai Padmashali",
        "artisan_phone": "+919876501003",
        "artisan_location": "Pochampally, Telangana",
        "category": "Handloom & Textiles",
        "price": 1650,
        "suggested_price_min": 1400,
        "suggested_price_max": 2000,
        "description_en": "Double-Ikat resist-dyed cotton dress material from Pochampally. The iconic geometric diamond pattern is created by dyeing yarn before weaving. 3-meter length, breathable cotton, suitable for kurta or salwar. GI-tagged Telangana weave.",
        "description_hi": "Pochampally se Double-Ikat cotton dress material. Bunai se pahle dhage ko rangkar banaya gaya.",
        "tags": "ikat,pochampally,cotton,dress-material,GI-tagged,telangana,resist-dye",
        "image_url": "/static/uploads/pochampally_ikat.jpg",
        "quantity": 12,
        "rating": 4.7,
    },
    {
        "name": "Kachchhi Bandhani Chiffon Dupatta with Mirror Work",
        "artisan_name": "Fatima Khatri",
        "artisan_phone": "+919876501004",
        "artisan_location": "Bhuj, Gujarat",
        "category": "Handloom & Textiles",
        "price": 1900,
        "suggested_price_min": 1600,
        "suggested_price_max": 2400,
        "description_en": "Luxurious Kachchhi hand-embroidered dupatta combining Bandhani tie-dye with mirror (abhla) work embroidery. Pure chiffon base with over 2000 individual hand-stitched mirrors. Traditional geometric patterns in magenta and gold. 2.25m x 1m.",
        "description_hi": "Bandhani tie-dye aur sheeshe ke kaam ke saath Kachchhi hast-kashidakari dupatta.",
        "tags": "bandhani,dupatta,gujarat,kachchh,mirror-work,embroidery,GI-tagged,chiffon",
        "image_url": "/static/uploads/bandhani_dupatta.jpg",
        "quantity": 15,
        "rating": 4.8,
    },
    # ── Pottery & Terracotta ──────────────────────────────────────────────────
    {
        "name": "Khurja Blue Pottery Ceramic Tea Set (6-piece)",
        "artisan_name": "Saleem Khan",
        "artisan_phone": "+919876501005",
        "artisan_location": "Khurja, Uttar Pradesh",
        "category": "Pottery & Terracotta",
        "price": 1250,
        "suggested_price_min": 1100,
        "suggested_price_max": 1600,
        "description_en": "Authentic Khurja blue pottery tea set comprising 1 teapot and 5 ceramic cups. Hand-painted with Persian-origin floral motifs in cobalt blue on white glazed background. Made from quartz-rich clay, lead-free food-safe glaze. GI-tagged Khurja pottery.",
        "description_hi": "Khurja Blue Pottery chai set, 1 chaydani aur 5 cup, haath se chitra phoolon ke saath.",
        "tags": "khurja,blue-pottery,ceramic,tea-set,GI-tagged,UP,food-safe,Persian-motif",
        "image_url": "/static/uploads/khurja_tea_set.jpg",
        "quantity": 20,
        "rating": 4.6,
    },
    {
        "name": "Jaipur Blue Pottery Decorative Flower Vase Set",
        "artisan_name": "Gopal Kumawat",
        "artisan_phone": "+919876501006",
        "artisan_location": "Jaipur, Rajasthan",
        "category": "Pottery & Terracotta",
        "price": 890,
        "suggested_price_min": 750,
        "suggested_price_max": 1100,
        "description_en": "Set of 2 Jaipur blue pottery vases in complementary sizes (30cm and 20cm). Handcrafted using Mughal-era Persian technique on quartz-based clay. Cobalt blue and white hand-painted floral motifs with turquoise accents. Persian-Rajputana fusion design.",
        "description_hi": "Jaipur Blue Pottery phooldan ka joda, Mughalkalin Farsi taknik se banaya gaya.",
        "tags": "jaipur,blue-pottery,vase,rajasthan,decor,persian-technique,cobalt",
        "image_url": "/static/uploads/blue_pottery_vase.jpg",
        "quantity": 18,
        "rating": 4.5,
    },
    {
        "name": "Warli Tribal Folk Art Terracotta Pot",
        "artisan_name": "Sukri Bhura",
        "artisan_phone": "+919876501007",
        "artisan_location": "Dahanu, Maharashtra",
        "category": "Pottery & Terracotta",
        "price": 580,
        "suggested_price_min": 450,
        "suggested_price_max": 720,
        "description_en": "Handcrafted terracotta pot decorated with traditional Warli tribal folk art. White pigment Warli murals depicting village life, dance, and harvest festival scenes on natural terracotta base. The ancient Adivasi painting tradition of Maharashtra.",
        "description_hi": "Paramparagat Warli adivasi kala se sushobhit hastnirmit terracotta bartan.",
        "tags": "warli,terracotta,tribal-art,maharashtra,folk-art,decor,pot",
        "image_url": "/static/uploads/warli_pot.jpg",
        "quantity": 25,
        "rating": 4.7,
    },
    # ── Brass & Metalcraft ────────────────────────────────────────────────────
    {
        "name": "Bastar Dhokra Lost-Wax Cast Tribal Musician Figurine",
        "artisan_name": "Suresh Baghel",
        "artisan_phone": "+919876501008",
        "artisan_location": "Kondagaon, Chhattisgarh",
        "category": "Brass & Metalcraft",
        "price": 2800,
        "suggested_price_min": 2400,
        "suggested_price_max": 3500,
        "description_en": "Authentic Bastar Dhokra figurine of a tribal musician playing the traditional Bastar flute. Crafted using the 4000-year-old lost-wax (cire perdue) casting technique with non-ferrous brass alloy. Each piece is unique. Height 22cm. GI-tagged craft.",
        "description_hi": "Bastar Dhokra, 4000 saal purani khoya-mom taknik se bana janjatiya sangeetkaar ka putla.",
        "tags": "dhokra,bastar,lost-wax,brass,tribal,chhattisgarh,figurine,GI-tagged",
        "image_url": "/static/uploads/dhokra_musician.jpg",
        "quantity": 10,
        "rating": 4.9,
    },
    {
        "name": "Moradabad Brass Engraved Peacock Decorative Plate",
        "artisan_name": "Hussain Mirza",
        "artisan_phone": "+919876501009",
        "artisan_location": "Moradabad, Uttar Pradesh",
        "category": "Brass & Metalcraft",
        "price": 1380,
        "suggested_price_min": 1100,
        "suggested_price_max": 1700,
        "description_en": "Moradabad-style brass decorative plate featuring intricately hand-engraved dancing peacock with spread tail feathers. 30cm diameter. Gold-toned brass with antique patina finish. Wall-mountable with back hooks. GI-recognized Moradabad brassware.",
        "description_hi": "Moradabad peetal ki sajawati plate jis par haath se nakkashidar mor bana hai.",
        "tags": "moradabad,brass,engraved,peacock,plate,GI-tagged,UP,decor,metalcraft",
        "image_url": "/static/uploads/brass_peacock_plate.jpg",
        "quantity": 14,
        "rating": 4.6,
    },
    # ── Woodcraft ─────────────────────────────────────────────────────────────
    {
        "name": "Channapatna Lacquerware Wooden Elephant Set (3 sizes)",
        "artisan_name": "Rajappa Gowda",
        "artisan_phone": "+919876501010",
        "artisan_location": "Channapatna, Karnataka",
        "category": "Woodcraft",
        "price": 680,
        "suggested_price_min": 550,
        "suggested_price_max": 850,
        "description_en": "Set of 3 Channapatna lacquerware elephants in descending sizes (Large 18cm, Medium 12cm, Small 8cm). Made from hale wood (Wrightia tinctoria) coated with natural lac color. Completely non-toxic and child-safe. GI-tagged Karnataka craft.",
        "description_hi": "Channapatna laakhkari teen hathiyon ka set, haale lakdi aur prakratik rang se bana.",
        "tags": "channapatna,lacquerware,wooden,elephant,karnataka,GI-tagged,non-toxic,child-safe",
        "image_url": "/static/uploads/channapatna_elephants.jpg",
        "quantity": 30,
        "rating": 4.8,
    },
    {
        "name": "Saharanpur Sheesham Wood Carved Jali Decorative Panel",
        "artisan_name": "Rafiq Ahmed",
        "artisan_phone": "+919876501011",
        "artisan_location": "Saharanpur, Uttar Pradesh",
        "category": "Woodcraft",
        "price": 3200,
        "suggested_price_min": 2800,
        "suggested_price_max": 4000,
        "description_en": "Decorative wall panel carved from solid seasoned Sheesham (Indian Rosewood) featuring intricate floral jali lattice fretwork. 60cm x 90cm, 2cm thick. Traditional Saharanpur style with Mughal geometric star patterns. Can be used as wall art or room divider.",
        "description_hi": "Saharanpur hastashilp mein sheesham ki lakdi se banaya gaya jali panel.",
        "tags": "saharanpur,sheesham,jali,wood-carving,rosewood,UP,wall-panel,mughal-pattern",
        "image_url": "/static/uploads/sheesham_jali.jpg",
        "quantity": 7,
        "rating": 4.7,
    },
    # ── Tribal Jewelry ────────────────────────────────────────────────────────
    {
        "name": "Bastar Filigree Oxidized Silver Tribal Necklace",
        "artisan_name": "Kamla Nag",
        "artisan_phone": "+919876501012",
        "artisan_location": "Jagdalpur, Chhattisgarh",
        "category": "Tribal Jewelry",
        "price": 950,
        "suggested_price_min": 800,
        "suggested_price_max": 1200,
        "description_en": "Bastar-style oxidized silver alloy tribal necklace with peacock and lotus motif pendants. Handcrafted using filigree technique where fine metal threads are twisted into intricate patterns. Adjustable length 45-55cm. Hypoallergenic alloy, nickel-free.",
        "description_hi": "Bastar shaili ki oxidized silver janjatiya haar, taar filigree taknik se bani.",
        "tags": "tribal,jewelry,necklace,bastar,chhattisgarh,filigree,oxidized-silver,peacock",
        "image_url": "/static/uploads/bastar_necklace.jpg",
        "quantity": 20,
        "rating": 4.6,
    },
    {
        "name": "Jaipur Kundan Meenakari Gold-Plated Chandelier Earrings",
        "artisan_name": "Devdas Soni",
        "artisan_phone": "+919876501013",
        "artisan_location": "Jaipur, Rajasthan",
        "category": "Tribal Jewelry",
        "price": 1600,
        "suggested_price_min": 1400,
        "suggested_price_max": 2000,
        "description_en": "Traditional Rajasthani Kundan-Meenakari chandelier earrings. 22-karat gold-plated brass base set with uncut polki-style glass stones and hand-painted enamel (meena) on reverse. Jaipur Meenakari is a 500-year-old royal art form. Approx 7cm drop, hook fastening.",
        "description_hi": "Jaipur Kundan-Meenakari jhumka, 22 karat sona chadhi hui peetal par hast chitra meena.",
        "tags": "kundan,meenakari,jaipur,rajasthan,earrings,gold-plated,royal-craft,GI-tagged",
        "image_url": "/static/uploads/kundan_earrings.jpg",
        "quantity": 25,
        "rating": 4.8,
    },
    # ── Folk Art & Painting ───────────────────────────────────────────────────
    {
        "name": "Madhubani Mithila Painting — Shiva Family Scene",
        "artisan_name": "Dulari Devi",
        "artisan_phone": "+919876501014",
        "artisan_location": "Madhubani, Bihar",
        "category": "Folk Art & Painting",
        "price": 2400,
        "suggested_price_min": 2000,
        "suggested_price_max": 3200,
        "description_en": "Original Madhubani Mithila painting on handmade cotton rag paper depicting Lord Shiva with Parvati, Ganesha, and Nandi in Godna style. Created by National Award artisan Dulari Devi. Natural earth pigments. 45cm x 60cm, unframed.",
        "description_hi": "Madhubani Mithila chitrakari, Rashtriya Puraskar vijeta Dulari Devi dwara hastnirmit kagaz par.",
        "tags": "madhubani,mithila-painting,folk-art,bihar,GI-tagged,natural-pigment,shiva,national-award",
        "image_url": "/static/uploads/madhubani_shiva.jpg",
        "quantity": 6,
        "rating": 5.0,
    },
    {
        "name": "Odisha Pattachitra Scroll Painting — Lord Jagannath",
        "artisan_name": "Apindra Moharana",
        "artisan_phone": "+919876501015",
        "artisan_location": "Raghurajpur, Odisha",
        "category": "Folk Art & Painting",
        "price": 3100,
        "suggested_price_min": 2600,
        "suggested_price_max": 4000,
        "description_en": "Authentic Pattachitra scroll painting from UNESCO-listed Raghurajpur village, Odisha. Depicts Lord Jagannath, Balabhadra, and Subhadra with temple chariot motifs. Painted on natural canvas (khadua) with 12 hand-ground mineral pigments and tamarind seed glue.",
        "description_hi": "Odisha Pattachitra scroll, Raghurajpur UNESCO virasat gaon se, Jagannath Mahaprabhu chitran.",
        "tags": "pattachitra,odisha,GI-tagged,scroll-painting,jagannath,raghurajpur,UNESCO,mineral-pigment",
        "image_url": "/static/uploads/pattachitra_jagannath.jpg",
        "quantity": 8,
        "rating": 4.9,
    },
    {
        "name": "Gond Tribal Art Painting — Tree of Life (Canvas)",
        "artisan_name": "Nankusia Shyam",
        "artisan_phone": "+919876501016",
        "artisan_location": "Patangarh, Madhya Pradesh",
        "category": "Folk Art & Painting",
        "price": 1800,
        "suggested_price_min": 1500,
        "suggested_price_max": 2400,
        "description_en": "Original Gond tribal painting on canvas depicting the iconic Tree of Life with birds, animals, and deity forms woven into intricate dot-dash patterns. By Nankusia Shyam from the famous Shyam family. Acrylic on canvas, 40cm x 50cm, framed.",
        "description_hi": "Gond janjatiya chitrakari, Jeevan Vriksh ke saath pakshiyon aur praniyon ka bindu-rekha chitran.",
        "tags": "gond,tribal-painting,madhya-pradesh,tree-of-life,dot-pattern,patangarh,canvas",
        "image_url": "/static/uploads/gond_tree.jpg",
        "quantity": 10,
        "rating": 4.7,
    },
    # ── Cane & Bamboo ────────────────────────────────────────────────────────
    {
        "name": "Assamese Bamboo Hand-Woven Wall Clock (Majuli Style)",
        "artisan_name": "Bijay Doley",
        "artisan_phone": "+919876501017",
        "artisan_location": "Majuli, Assam",
        "category": "Cane & Bamboo",
        "price": 750,
        "suggested_price_min": 600,
        "suggested_price_max": 950,
        "description_en": "Decorative wall clock with face crafted from hand-woven bamboo in Assamese Majuli style, incorporating traditional tribal hexagonal weave pattern. Silent quartz AA-battery mechanism included. 30cm diameter. Frame woven from Muli bamboo split.",
        "description_hi": "Asami Majuli shaili mein buna gaya baas ka deewar ghadi, shaant quartz yantra sahit.",
        "tags": "bamboo,assam,majuli,wall-clock,handwoven,cane,tribal-weave",
        "image_url": "/static/uploads/bamboo_wall_clock.jpg",
        "quantity": 22,
        "rating": 4.5,
    },
    {
        "name": "Tripura Rattan Reed Oval Fruit Basket with Lid",
        "artisan_name": "Brishali Deb",
        "artisan_phone": "+919876501018",
        "artisan_location": "Agartala, Tripura",
        "category": "Cane & Bamboo",
        "price": 620,
        "suggested_price_min": 500,
        "suggested_price_max": 800,
        "description_en": "Oval wicker basket woven from locally harvested Tripura rattan reed with hinged lid and braided natural handle. Multi-purpose: fruit storage, bread basket, or picnic hamper. Natural and sustainable, each piece unique. Size: 35cm x 25cm x 20cm.",
        "description_hi": "Tripura ratan bet se buni hui andakar tokari, dhakkan aur prakratik handle ke saath.",
        "tags": "rattan,basket,tripura,cane,handwoven,eco-friendly,storage",
        "image_url": "/static/uploads/rattan_basket.jpg",
        "quantity": 28,
        "rating": 4.4,
    },
    # ── Leather Craft ─────────────────────────────────────────────────────────
    {
        "name": "Kolhapuri Hand-Stitched Vegetable-Tanned Leather Chappal",
        "artisan_name": "Ganesh Kambli",
        "artisan_phone": "+919876501019",
        "artisan_location": "Kolhapur, Maharashtra",
        "category": "Leather Craft",
        "price": 880,
        "suggested_price_min": 750,
        "suggested_price_max": 1100,
        "description_en": "Authentic Kolhapuri chappal handcrafted from vegetable-tanned cow hide leather with hand-punched floral medallion design on strap. GI-tagged, exported to 40+ countries. Flat sole with hand-stitched edge. Available in Men's sizes 6-12.",
        "description_hi": "Kolhapuri chappal, vanaspati-ranjit bachhde ki khaal se haath se bani, GI-manyata prapt.",
        "tags": "kolhapuri,chappal,leather,maharashtra,GI-tagged,vegetable-tanned,handstitched,sandal",
        "image_url": "/static/uploads/kolhapuri_chappal.jpg",
        "quantity": 40,
        "rating": 4.7,
    },
    # ── Stone Carving ─────────────────────────────────────────────────────────
    {
        "name": "Mahabalipuram Granite Nataraja Dancing Shiva Sculpture",
        "artisan_name": "R. Dhandapani",
        "artisan_phone": "+919876501021",
        "artisan_location": "Mahabalipuram, Tamil Nadu",
        "category": "Stone Carving",
        "price": 4500,
        "suggested_price_min": 4000,
        "suggested_price_max": 5500,
        "description_en": "Exquisitely hand-carved Nataraja (Cosmic Dancer) sculpture in black Krishnagiri granite. Depicts Shiva performing the Ananda Tandava surrounded by the ring of fire (prabhamandala). Height 35cm. Mahabalipuram Pallava tradition, 7th century style.",
        "description_hi": "Mahabalipuram Krishnagiri granite mein haath se taraashi gayi Nataraaja pratima, 7vi sadi Pallava parampara.",
        "tags": "nataraja,granite,stone-carving,mahabalipuram,tamil-nadu,GI-tagged,shiva,pallava,sculpture",
        "image_url": "/static/uploads/granite_nataraja.jpg",
        "quantity": 4,
        "rating": 4.9,
    },
    {
        "name": "Kondapalli Kinnal Wooden Dancing Ganesha Toy",
        "artisan_name": "P. Venkateswara Rao",
        "artisan_phone": "+919876501020",
        "artisan_location": "Kondapalli, Andhra Pradesh",
        "category": "Woodcraft",
        "price": 560,
        "suggested_price_min": 450,
        "suggested_price_max": 700,
        "description_en": "Traditional Kondapalli Kinnal wooden toy of Dancing Ganesha made from tella poniki (white sago) wood. Painted with natural organic pigments in vivid festival colors. Used in traditional temple processions and home decor. Height 18cm. GI-tagged Andhra craft.",
        "description_hi": "Kondapalli Kinnal shilp mein naachte Ganesha ka lakdi ka khilona, prakratik rangon se chitra.",
        "tags": "kondapalli,wooden-toy,ganesha,andhra-pradesh,GI-tagged,kinnal,folk-toy,natural-pigment",
        "image_url": "/static/uploads/kondapalli_ganesha.jpg",
        "quantity": 35,
        "rating": 4.8,
    },
]


def seed():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    inserted = 0
    skipped = 0
    for p in PRODUCTS:
        cur.execute("SELECT id FROM products WHERE name = ?", (p["name"],))
        if cur.fetchone():
            print(f"  SKIP (exists): {p['name'][:60]}")
            skipped += 1
            continue

        cur.execute("""
            INSERT INTO products (
                name, artisan_name, artisan_phone, artisan_location,
                category, price, suggested_price_min, suggested_price_max,
                description_en, description_hi, tags, image_url,
                quantity, rating, is_enhanced, mosje_verified
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1, 1)
        """, (
            p["name"], p["artisan_name"], p.get("artisan_phone", "+919876543210"),
            p["artisan_location"], p["category"], p["price"],
            p.get("suggested_price_min", p["price"]), p.get("suggested_price_max", p["price"]),
            p["description_en"], p.get("description_hi", ""), p["tags"], p["image_url"],
            p.get("quantity", 5), p.get("rating", 4.5)
        ))
        print(f"  ADDED: {p['name'][:60]}")
        inserted += 1

    conn.commit()
    conn.close()
    print(f"\nDone! Inserted {inserted} products, skipped {skipped} duplicates.")


if __name__ == "__main__":
    seed()
